### ISSUE TITLE
Documentation for using the base icons

### ISSUE THREAD

**Issue by jancel** [Qonfucius/nuxt-fontawesome#1]
I was able to get the free business pack working just fine, but having tried to configure other packs or the base icons, I can't find the documentation for this.

**Comment by pand-app** [comment]
Hello @jancel, to install free solid pack, you've to add `@fortawesome/fontawesome-free-solid` package. As fontawesome 5 is not yet released, all icons seems to not yet be available (light/bold). But solid package exists

**Comment by jancel** [comment]
I had figured that out and thought about updating the doc. I also see
that’s part of the fas, and see it means free and solid. Is there a list of
packages I can cross-reference so we can add it in the doc? I can make a
pull request if I can find something exhaustive.

**Comment by jancel** [comment]
Thanks for the information. I am going to close as resolved.

**Comment by rlam3** [comment]
@jancel was wondering if you had a working example with this module. I'm having difficulty integrating with nuxt.js app. Thanks!
