### ISSUE TITLE
Is possible to provide a working example?

### ISSUE THREAD

**Issue by rlam3** [Qonfucius/nuxt-fontawesome#3]
Is possible to provide a working example? Thank you for your great work @Nainterceptor 

I keep on getting the following error: 

```js
did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by pand-app** [comment]
Hello @rlam3. I've just added the minimum working project that I'm able to provide. Please see in "examples" folder.

Have a nice day
