### ISSUE TITLE
Icons load incorrectly (very large) in server side

### ISSUE THREAD

**Issue by Kidounet** [Qonfucius/nuxt-fontawesome#7]
Hello,

for this issue : https://github.com/FortAwesome/vue-fontawesome/issues/14

i put fontawesome style.css in nuxt.config.js :

    css: [
        '@fortawesome/fontawesome/styles.css',
    ],

Can you see how to resolve this without manualy adding something, or add a comment in the readme.md ?

Thanks

**Comment by pand-app** [comment]
Hello @Kidounet, Thanks for your report.

Do you have few time to check the pull request ?

Else, will be merged soon.

**Comment by pand-app** [comment]
Merged. Thanks !
